### PR TITLE
EmailList - Change variable names to stop Invoke-Command loop

### PR DESCRIPTION
**Pull request by natosullivan**
The below code loops indefinitely until the call depth limit is reached:

```powershell
Email -Port 25 {
        EmailHeader {
            EmailFrom -Address 'test@test.com'
            EmailTo -Addresses "test@test.net"
            EmailServer -Server 'mail.test.com'
            EmailOptions -Priority High -DeliveryNotifications Never
            EmailSubject -Subject 'This is a test email'
        }
        EmailBody -FontFamily 'Calibri' -Size 15 {
            EmailTextBox -FontSize 18 -TextDecoration underline -FontWeight Bold {
                "Test Email"
            }
            EmailText -LineBreak
            EmailList {
                EmailListItem -Text "NotNull"
            }
        }
    } -Supress:$false
```

Looks to be caused by the script block variables in EmailList and New-HTMLEmailList being named the same, causing the Invoke-Command to create a loop.

Resolved by changing the script block variable name in New-HTMLEmailList to $HTMLListItems

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
Changing the variable name without changing params

https://github.com/EvotecIT/PSWriteHTML/blob/4405b7db27cfba37bb1a7507a4f4cfd6b3bcdb8f/Public/New-HTMLList.ps1#L4-L4

Is going to break that function. The proper fix is to merge New-HTMLList with EmailList by making EmailList an alias. Now that emailimo is merged into PSWriteHTML some stuff is doubled.

**Comment by PrzemyslawKlys** [comment]
I've tested this by just running the old code and it never returned error but than the email that arrived didn't had that EmailList. I did a test change per your suggestion 

image

And it seems to fix the issue. But I believe we should get rid of EmailList and just make it an alias. Will you fix it?

**Comment by natosullivan** [comment]
That is a much cleaner way to resolve this, I have added the alias to New-HTMLList.

**Comment by PrzemyslawKlys** [comment]
Looks good. Thank you

**Pull request merged**
