### PR TITLE
Code I added to ReportHtml

### PR DESCRIPTION
**Pull request by spaelling**
Solution for adding images and hyperlinks to reports. Below showcases how it would work

```
$ArrayOfObjects = New-Object 'System.Collections.Generic.List[System.Object]'
$obj = [PSCustomObject]@{
    param1 = [PSCustomObject]@{
        _type = 'img'
        src = 'http://ihavecat.com/wp-content/uploads/2014/01/cat-asking-for-help-2.jpg'
        alt = 'cat asking for help'
        width = 60
        height = 60
    }
    param2 = [PSCustomObject]@{
        _type = 'link'
        url = 'https://www.w3schools.com'
        target = '_blank'
        Content = 'Visit w3schools!'
    }
    param3 = 'simpleparam'
    param4 = [PSCustomObject]@{
        _type = 'link'
        url = 'http://ihavecat.com/wp-content/uploads/2014/01/cat-asking-for-help-2.jpg'
        target = '_blank'
        Content = [PSCustomObject]@{
            _type = 'img'
            src = 'http://ihavecat.com/wp-content/uploads/2014/01/cat-asking-for-help-2.jpg'
            alt = 'cat asking for help'
            width = 60
            height = 60
        }
    }
}
$ArrayOfObjects.Add($obj)
```
These 3 helper functions are used
```
Format-AnchorTag.ps1
Format-Html.ps1
Format-ImageTag.ps1
```
I updated `Get-HTMLContentTable.ps1` with the code needed to utilize these.

For line charts I added
```
Get-HTMLLineChartObject.ps1
Get-HTMLLineChart.ps1
```

You can see how that could work here [https://github.com/spaelling/PowerShellSpeedTest/blob/master/Loops.ps1](https://github.com/spaelling/PowerShellSpeedTest/blob/master/Loops.ps1)

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
Thanks. I'm sure it will get useful. I do expect to rename most of the functions and slightly rebuild how things are. You may need to come back to this and help me out to get this to the level you desire ;)

I already changed some names and used -Open / -Close switch instead of separate function names. But most likely  I will go much further. Hope you're ok with it.

**Comment by spaelling** [comment]
I am perfectly ok with renaming the functions. Aliases and dummy functions can get a long way, like below

```
function Get-HtmlContentOpen
{
   param(...)
   Get-HtmlContent -Open @PsBoundParameters 
}
```

I think that open and close switches makes sense. I do not particularly like the whole way of building up the html, but this would help.

Also passing the html variable to the function would get rid of the endless Add or +=. This could be made easier if using $PSDefaultParameterValues

**Comment by PrzemyslawKlys** [comment]
I was thinking to use a pipeline to some extent. Was also wondering if it's possible to automatically close some stuff by using PSAutomator approach or how Pester does it. But that needs some heavy work

```powershelll
New-HtmlHeader
New-HtmlPage {
    New-HtmlTab {
        Get-HtmlContentDataTable
    }
    New-HtmlTab {
        New-HtmlContent {
            Get-HtmlContentDataTable
        }
        New-HtmlContent {
            Get-HtmlContentDataTable
        }
    }
}
```
This would allow autoformatting to work properly.

**Comment by spaelling** [comment]
yes, something like that would be awesome. 

Would those be scriptblocks that have to be invoked, or how would that work?

**Comment by spaelling** [comment]
something like this

```
function func1 {
    param (
        $scriptblock
    )
    
    
    "func1 html`n" +  (Invoke-Command -ScriptBlock $scriptblock)
}

function func2 {
    param (
        $scriptblock = { ""}
    )
    
    "func2 html " + (Invoke-Command -ScriptBlock $scriptblock)
}

func1 {
    func2 
}
```

**Comment by PrzemyslawKlys** [comment]
Basically, it will look like this. Of course, for now, there's only one function like that. Probably each function that has a process similar to opening up <HTML><BODY> and so on will need the same approach. 

```powershell
Function New-HtmlPage {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true, Position = 0)][string] $Name,
        [Parameter(Position = 1)][ValidateNotNull()][ScriptBlock] $ServiceData = $(Throw "No test script block is provided. (Have you put the open curly brace on the next line?)"),
        [switch] $UseCssLinks,
        [switch] $UseStyleLinks
    )
    Begin {}
    Process {
        $HTML = "<HTML>"
        $HTML += Add-HTMLHead -UseStyleLinks:$UseStyleLinks -UseCssLinks:$UseCssLinks
        $HTML += "<BODY>"
        $HTML += Invoke-Command -ScriptBlock $ServiceData
        $HTML += "</BODY>"
    }
    End {
        $HTML += "</HTML>"
        return $HTML
    }
}


$HTML = New-HtmlPage -Name 'Test' -UseCssLinks -UseStyleLinks {
    Get-HTMLTab {
        Get-HTMLContent -HeaderText 'Test' {
            Get-HTMLContent -HeaderText 'Something else' {
                Get-HTMLContentTable $MyTable1
                Get-HTMLContentTable $MyTable2
            }
        }
    }
}
Save-HTML -FilePath "myTest.html" -ShowHTML -HTML $HTML
```

**Comment by PrzemyslawKlys** [comment]
Lets move this discussion to issue https://github.com/EvotecIT/PSWriteHTML/issues/6

**Pull request merged**
