### PR TITLE
Targetted DataTable recalc for tabs and sections

### PR DESCRIPTION
**Pull request by opustecnica**
Please test this changes to verify they are aligned with goals/intentions.  Note that if a tab contains a collapsed/hidden section, its content is not refreshed until the section is fully shown.

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
Wow :-)

**Comment by PrzemyslawKlys** [comment]
It's very clever.

I got this error while refreshing

image

**Comment by PrzemyslawKlys** [comment]
it seems to work partially. The error happens from time to time. 

[TestimoCompare.zip](https://github.com/EvotecIT/PSWriteHTML/files/4104759/TestimoCompare.zip)

It's much faster but seems to be struggling with refreshing some tabs correctly.

**Comment by PrzemyslawKlys** [comment]
But maybe it's me pressing too fast or refreshing during wait time?

**Comment by opustecnica** [comment]
Wow, that is a big report :-)
About the error above, it seems the issue is about attempting to re-initialize a table. (https://datatables.net/manual/tech-notes/3).  While there are ways to remedy this, I would like to understand the root-cause.  The portions of code modified only deal with the recalc of an already initialized table.  The only time I can see this happening is if two tables are mistakenly assigned the same ID.  Could you please send the test code and the html output of the page that causes this issue?  I want to make sure that other, seemingly unrelated, changes are not contributing to the issue.  I have run my tests with 0.071 and applied only PRs 100 and 105.

**Comment by PrzemyslawKlys** [comment]
I'm using this one:

```
Import-Module .\PSWriteHTML.psd1 -Force

$Test = Get-Process #| Select-Object -First 2 #-Property Name, Id,PriorityClass, HandleCount, WorkingSet

New-HTML -TitleText 'My title' -UseCssLinks:$true -UseJavaScriptLinks:$true -FilePath $PSScriptRoot\Example-Tabs01-Old.html -Show {
    New-HTMLTabOptions -SlimTabs -Transition -LinearGradient -SelectorColor Gold -SelectorColorTarget AliceBlue
    New-HTMLTab -Name 'Test 1' -IconBrands acquisitions-incorporated -IconColor Coriander {
        New-HTMLTab -Name 'Nested Tab 1' {
            New-HTMLSection -Invisible {
                New-HTMLPanel {
                    New-HTMLTable -DataTable $Test
                }
                New-HTMLPanel {
                    New-HTMLChart -Gradient {
                        New-ChartPie -Name 'Test' -Value 20
                        New-ChartPie -Name 'Test1' -Value 30
                        New-ChartPie -Name 'Test2' -Value 40
                        New-ChartPie -Name 'Test1' -Value 30
                        New-ChartPie -Name 'Test2' -Value 40
                    }
                }
            }
        }
        New-HTMLTab -Name 'Nested Tab 2' {
            New-HTMLSection -HeaderText 'Test' -HeaderBackGroundColor BrightRed {
                New-HTMLTable -DataTable $Test
            }
        }
    }
    New-HTMLTab -Name 'Test 2' -IconRegular check-circle -IconColor LightSkyBlue {
        New-HTMLTable -DataTable $Test -DisablePaging
    }

    New-HTMLTab -Name 'Test 3' -IconSolid code-branch -IconColor LimeGreen {
        New-HTMLTable -DataTable $Test
        New-HTMLSection -HeaderText 'Test' -HeaderBackGroundColor CottonCandy {

        }
    }
    New-HTMLTab -Name 'Test 4' -IconSolid bezier-curve {
        New-HTMLTable -DataTable $Test -DisablePaging
    }
    New-HTMLTab -Name 'Test 5' -IconSolid copy -IconColor BrinkPink {
        New-HTMLTable -DataTable $Test
    }
    New-HTMLTab -Name 'Test' -IconBrands asymmetrik {
        New-HTMLTable -DataTable $Test
    }
    New-HTMLTab -Name 'Test' -IconRegular kiss-beam -TextColor BritishRacingGreen {
        New-HTMLTable -DataTable $Test -DisablePaging
    }
}
```

However for Testimo .. well you need Active Directory to run it. 

```
$TestResults = Invoke-Testimo -ShowReport:$true -ReturnResults
```

But I was getting that error on the 1st code as well.

**Comment by opustecnica** [comment]
:-( I cannot replicate :-(
... But maybe it's me pressing too fast or refreshing during wait time? ...
I honestly suspect that to be the case.  If the full document is not ready, we risk to request the re-initialization of an object that is in process of initialization.  I usually work on simpler layouts 3-4 tabs max, but with large tables (1k plus records).  To avoid issues, I am working on a simple "...wait while we load content..."  to caution users from refreshing.  For cases like the one above, I am contemplating importing the original collection ($test) in to a JS var and build tables on the fly via JS.  That way I only need to import the data once vs every time I need to display it.

**Comment by PrzemyslawKlys** [comment]
Ye, that would be cool having a progress bar that shows something is happening. Like if page is loading it doesn't look pretty. Also it doesn't look pretty if user has to wait 10 seconds to switch tabs and he has no clue what is happening.

**Comment by PrzemyslawKlys** [comment]
As for other stuff.. all that stuff is cool :-) just time ...

**Comment by PrzemyslawKlys** [comment]
Do you think we should merge it and later on work on improvements or do you want to keep it open until more tests are done?

**Comment by opustecnica** [comment]
In one hand I would like to spend some time taking care of testing and the “wait while” loading feature. On the other I believe the current “reload all” behavior is so debilitating that needs immediate addressing. Thoughts?

**Comment by PrzemyslawKlys** [comment]
I'll be testing the wait while loading - I found some library for that (opened an issue with it). Maybe it will help.

**Pull request merged**
