### PR TITLE
Table Conditional Formatting for Date Strings

### PR DESCRIPTION
**Pull request by xlrod**
Added a switch to handle the comparison for date strings inside the `elseif` for date.
Added `date` to the `$ComparisonType` validate set.
When using the `eq` and `ne`, it's going to use strings to compare. The value that's used to compare to the table must be the same, otherwise it won't be able to find it is equal/not equal. 
(Eg: Table value = 12/1/2019 10:00 AM; `-Value "12/1/2019 10:00 AM"`). 
For the other operators it will use date.

dateCompare

    $Table = @()
    $Table = 0..5 | ForEach-Object { [PSCustomObject] @{
            "Name" = (Get-RandomStringName -LettersOnly -Size 5)
            "Date" = (Get-Date).AddDays("-" + $(Get-Random -Minimum 1 -Maximum 10))
        }
    }

    $Table2 = @()
    $Table2 = 0..5 | ForEach-Object { [PSCustomObject] @{
            "Name" = (Get-RandomStringName -LettersOnly -Size 5)
            "Date" = ((Get-Date).AddDays("-" + $(Get-Random -Minimum 1 -Maximum 10))).ToString("MM/dd/yyyy")
        }
    }

    $Value = $Table[(Get-Random -Minimum 0 -Maximum ($Table.Count - 1))].Date.ToString("MM/dd/yyyy h:mm:ss tt")
    $Value2 = $Table2[(Get-Random -Minimum 0 -Maximum ($Table2.Count - 1))].Date

    New-HTML -TitleText "test" -FilePath "$PSScriptRoot\test.html" {

        New-HTMLSection -Invisible -Content { 

            New-HTMLSection -HeaderText "Less than: $Value" -Content {
                New-HTMLTable -DataTable $Table {
                    New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator lt -Value $Value -BackgroundColor LightBlue
                }
            }
            New-HTMLSection -HeaderText "Greater than: $Value" -Content {
                New-HTMLTable -DataTable $Table {
                    New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator gt -Value $Value -BackgroundColor LightBlue
                }
            }
            New-HTMLSection -HeaderText "Less than or equal: $Value" -Content {
                New-HTMLTable -DataTable $Table {
                    New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator le -Value $Value -BackgroundColor LightBlue
                }
            }
            New-HTMLSection -HeaderText "Greater than or equal: $Value" -Content {
                New-HTMLTable -DataTable $Table {
                    New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ge -Value $Value -BackgroundColor LightBlue
                }
            }
            New-HTMLSection -HeaderText "Equal: $Value" -Content {     
                New-HTMLTable -DataTable $Table {
                    New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator eq -Value $Value -BackgroundColor LightBlue
                }
            }
            New-HTMLSection -HeaderText "Not Equal: $Value" -Content {
                New-HTMLTable -DataTable $Table {
                    New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ne -Value $Value -BackgroundColor LightBlue
                }        
            }
        }

        New-HTMLSection -Invisible -Content { 

            New-HTMLSection -HeaderText "Less than: $Value2" -Content {
                New-HTMLTable -DataTable $Table2 {
                    New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator lt -Value $Value2 -BackgroundColor LightBlue
                }
            }
            New-HTMLSection -HeaderText "Greater than: $Value2" -Content {
                New-HTMLTable -DataTable $Table2 {
                    New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator gt -Value $Value2 -BackgroundColor LightBlue
                }
            }
            New-HTMLSection -HeaderText "Less than or equal: $Value2" -Content {
                New-HTMLTable -DataTable $Table2 {
                    New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator le -Value $Value2 -BackgroundColor LightBlue
                }
            }
            New-HTMLSection -HeaderText "Greater than or equal: $Value2" -Content {
                New-HTMLTable -DataTable $Table2 {
                    New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ge -Value $Value2 -BackgroundColor LightBlue
                }
            }
            New-HTMLSection -HeaderText "Equal: $Value2" -Content {     
                New-HTMLTable -DataTable $Table2 {
                    New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator eq -Value $Value2 -BackgroundColor LightBlue
                }
            }
            New-HTMLSection -HeaderText "Not Equal: $Value2" -Content {
                New-HTMLTable -DataTable $Table2 {
                    New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ne -Value $Value2 -BackgroundColor LightBlue
                }        
            }
        }
    }

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
I think it would be great idea to have those examples added to examples so it doesn't vanish and users can use those to test things out. Maybe same thing could be done for your other PR's? What do you think? I

I'm currently testign your changes.

**Comment by xlrod** [comment]
Will do, thanks!

**Comment by PrzemyslawKlys** [comment]
It doesn't seem to work or I am testing it wrong.

image

Notice that i'm from PL and my date display is different...  it seems more complicated or am I missing something?

**Comment by xlrod** [comment]
Missed that part, I'll do more testing with `Get-Culture` and edit the code.

**Comment by xlrod** [comment]
After further testing, these were my findings:
Date Format: dd.MM.yyyy
$tableDate = 05.12.2019
$compareDate = '04.12.2019'

The script will use the JS part:
`if (new Date('05.12.2019') < new Date('04.12.2019'))`
The `new Date('05.12.2019')` will use `MM.dd.yyyy` and convert it to May 12, 2019.
The same thing for the second `new Date` which results in: `May 12, 2019 < April 12, 2019`.
I tried using `Intl.DateTimeFormat` to get the local culture, but since the new date is being generated before I'm able to properly format it, it doesn't work properly.

To get accurate results, I found that the date format needs to start with the month or year, if it starts with the day, the JS part will not do the compare correctly. Tested with these date separators: `.`, `/`, `-`

dateformat



    Import-Module -Name PSWriteHTML -Force

    $format = "yyyy-MM-dd HH:mm:ss"
    $format2 = "yyyy-MM-dd"
    $format3 = "MM-dd-yyyy HH:mm:ss"
    $format4 = "MM-dd-yyyy"
    $format5 = "dd-MM-yyyy" # This won't work

    $Table = @()
    $Table = 0..5 | ForEach-Object { [PSCustomObject] @{
            "Name" = (Get-RandomStringName -LettersOnly -Size 5)
            "Date" = Get-Date -Date (Get-Date).AddDays("-" + $(Get-Random -Minimum 1 -Maximum 10)) -Format ($format)
        }
    }
    $Table2 = @()
    $Table2 = 0..5 | ForEach-Object { [PSCustomObject] @{
            "Name" = (Get-RandomStringName -LettersOnly -Size 5)
            "Date" = Get-Date -Date (Get-Date).AddDays("-" + $(Get-Random -Minimum 1 -Maximum 10)) -Format ($format2)
        }
    }
    $Table3 = @()
    $Table3 = 0..5 | ForEach-Object { [PSCustomObject] @{
            "Name" = (Get-RandomStringName -LettersOnly -Size 5)
            "Date" = Get-Date -Date (Get-Date).AddDays("-" + $(Get-Random -Minimum 1 -Maximum 10)) -Format ($format3)    
        }
    }
    $Table4 = @()
    $Table4 = 0..5 | ForEach-Object { [PSCustomObject] @{
            "Name" = (Get-RandomStringName -LettersOnly -Size 5)
            "Date" = Get-Date -Date (Get-Date).AddDays("-" + $(Get-Random -Minimum 1 -Maximum 10)) -Format ($format4)   
        }
    }
    $Table5 = @()
    $Table5 = 0..5 | ForEach-Object { [PSCustomObject] @{
            "Name" = (Get-RandomStringName -LettersOnly -Size 5)
            "Date" = Get-Date -Date (Get-Date).AddDays("-" + $(Get-Random -Minimum 1 -Maximum 10)) -Format ($format5)   
        }
    }

    $Value = $Table[(Get-Random -Minimum 0 -Maximum ($Table.Count - 1))].Date
    $Value2 = $Table2[(Get-Random -Minimum 0 -Maximum ($Table2.Count - 1))].Date
    $Value3 = $Table3[(Get-Random -Minimum 0 -Maximum ($Table3.Count - 1))].Date
    $Value4 = $Table4[(Get-Random -Minimum 0 -Maximum ($Table4.Count - 1))].Date

    New-HTML -TitleText "test" -FilePath "$PSScriptRoot\test.html" {
        New-HTMLSection -HeaderText "yyyy-MM-dd HH:mm:ss" -CanCollapse -Content {
            New-HTMLSection -Invisible -Content { 

                New-HTMLSection -HeaderText "Less than: $Value" -Content {
                    New-HTMLTable -DataTable $Table -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator lt -Value $Value -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Greater than: $Value" -Content {
                    New-HTMLTable -DataTable $Table -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator gt -Value $Value -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Less than or equal: $Value" -Content {
                    New-HTMLTable -DataTable $Table -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator le -Value $Value -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Greater than or equal: $Value" -Content {
                    New-HTMLTable -DataTable $Table -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ge -Value $Value -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Equal: $Value" -Content {     
                    New-HTMLTable -DataTable $Table -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator eq -Value $Value -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Not Equal: $Value" -Content {
                    New-HTMLTable -DataTable $Table -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ne -Value $Value -BackgroundColor LightBlue
                    }        
                }
            }
        }
        New-HTMLSection -HeaderText "yyyy-MM-dd" -CanCollapse -Collapsed -Content {
            New-HTMLSection -Invisible -Content { 

                New-HTMLSection -HeaderText "Less than: $Value2" -Content {
                    New-HTMLTable -DataTable $Table2 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator lt -Value $Value2 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Greater than: $Value2" -Content {
                    New-HTMLTable -DataTable $Table2 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator gt -Value $Value2 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Less than or equal: $Value2" -Content {
                    New-HTMLTable -DataTable $Table2 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator le -Value $Value2 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Greater than or equal: $Value2" -Content {
                    New-HTMLTable -DataTable $Table2 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ge -Value $Value2 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Equal: $Value2" -Content {     
                    New-HTMLTable -DataTable $Table2 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator eq -Value $Value2 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Not Equal: $Value2" -Content {
                    New-HTMLTable -DataTable $Table2 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ne -Value $Value2 -BackgroundColor LightBlue
                    }        
                }
            }
        }
        New-HTMLSection -HeaderText "MM-dd-yyyy HH:mm:ss" -CanCollapse -Collapsed -Content {
            New-HTMLSection -Invisible -Content { 

                New-HTMLSection -HeaderText "Less than: $Value3" -Content {
                    New-HTMLTable -DataTable $Table3 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator lt -Value $Value3 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Greater than: $Value3" -Content {
                    New-HTMLTable -DataTable $Table3 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator gt -Value $Value3 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Less than or equal: $Value3" -Content {
                    New-HTMLTable -DataTable $Table3 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator le -Value $Value3 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Greater than or equal: $Value3" -Content {
                    New-HTMLTable -DataTable $Table3 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ge -Value $Value3 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Equal: $Value3" -Content {     
                    New-HTMLTable -DataTable $Table3 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator eq -Value $Value3 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Not Equal: $Value3" -Content {
                    New-HTMLTable -DataTable $Table3 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ne -Value $Value3 -BackgroundColor LightBlue
                    }        
                }
            }
        }
        New-HTMLSection -HeaderText "MM-dd-yyyy" -CanCollapse -Collapsed -Content {
            New-HTMLSection -Invisible -Content { 

                New-HTMLSection -HeaderText "Less than: $Value4" -Content {
                    New-HTMLTable -DataTable $Table4 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator lt -Value $Value4 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Greater than: $Value4" -Content {
                    New-HTMLTable -DataTable $Table4 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator gt -Value $Value4 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Less than or equal: $Value4" -Content {
                    New-HTMLTable -DataTable $Table4 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator le -Value $Value4 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Greater than or equal: $Value4" -Content {
                    New-HTMLTable -DataTable $Table4 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ge -Value $Value4 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Equal: $Value4" -Content {     
                    New-HTMLTable -DataTable $Table4 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator eq -Value $Value4 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Not Equal: $Value4" -Content {
                    New-HTMLTable -DataTable $Table4 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ne -Value $Value4 -BackgroundColor LightBlue
                    }        
                }
            }
        }
        New-HTMLSection -HeaderText "This format won't work: dd-MM-yyyy" -CanCollapse -Collapsed -Content {
            New-HTMLSection -Invisible -Content { 

                New-HTMLSection -HeaderText "Less than: $Value5" -Content {
                    New-HTMLTable -DataTable $Table5 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator lt -Value $Value5 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Greater than: $Value5" -Content {
                    New-HTMLTable -DataTable $Table5 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator gt -Value $Value5 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Less than or equal: $Value5" -Content {
                    New-HTMLTable -DataTable $Table5 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator le -Value $Value5 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Greater than or equal: $Value5" -Content {
                    New-HTMLTable -DataTable $Table5 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ge -Value $Value5 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Equal: $Value5" -Content {     
                    New-HTMLTable -DataTable $Table5 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator eq -Value $Value5 -BackgroundColor LightBlue
                    }
                }
                New-HTMLSection -HeaderText "Not Equal: $Value5" -Content {
                    New-HTMLTable -DataTable $Table5 -DisableSearch -DefaultSortColumn "Date" {
                        New-HTMLTableCondition -Name "Date" -ComparisonType date -Operator ne -Value $Value5 -BackgroundColor LightBlue
                    }        
                }
            }
        }
    } -ShowHTML

**Comment by PrzemyslawKlys** [comment]
So you're basically forcing use to define the date in the proper format?

Maybe we could somehow utilize what is used for DateTimeSorting? 

https://github.com/EvotecIT/PSWriteHTML/blob/67895d64b1a64ac925e8d8681c065620cb2afff8/Public/New-HTMLTable.ps1#L479-L479

Just there are not a lot of know-how in this area. For example: https://github.com/EvotecIT/PSWriteHTML/issues/28 

Also keep in mind that there are 2 ways of table conditioning. One using JS which is what you're trying to solve. And one is Inline which is using:

https://github.com/EvotecIT/PSWriteHTML/blob/67895d64b1a64ac925e8d8681c065620cb2afff8/Public/New-TableCondition.ps1#L49-L52

https://github.com/EvotecIT/PSWriteHTML/blob/67895d64b1a64ac925e8d8681c065620cb2afff8/Public/New-HTMLTable.ps1#L108-L109

https://github.com/EvotecIT/PSWriteHTML/blob/67895d64b1a64ac925e8d8681c065620cb2afff8/Public/New-HTMLTable.ps1#L94-L95

And this is done on PowerShell Level. This needs to cover DateTime as well. 

I am not sure if we can leave this the way you proposed because that's a bit too complicated for user. Me as a "noob" I would like for it to just work. Maybe there's better date comparison option in JavaScript?

**Comment by xlrod** [comment]
I'll continue to research this. I have some more things I'd like to try.

**Comment by xlrod** [comment]
I've been testing this with the `moment()` js code and it has been working so far, but I need to specify which date format I'm using. For example, `$date = '11.12.2019 5:30:00'`, I would need to specify that this is `DD.MM.YYYY H:mm:ss` with moment. `moment('11.12.2019 5:30:00', 'DD.MM.YYYY H:mm:ss')` If no date format is specified it would default to locale, in my case ('MM/DD/YYYY'). I'm still trying to figure out how to do this without the need to specify a format.

**Comment by PrzemyslawKlys** [comment]
That's the tricky part. It's the same for sorting. Currently, you need to specify it. I wonder if it's solvable on PS level. It's possible HTML will be sent to the person to a different country so the sorting/comparison will be different. I believe this has to be solved on JS level with some sort of autotection.

**Comment by xlrod** [comment]
This needs more research.

**Pull request closed without merging**
